name: "Terraform Plan.."

on: [push]

env:
  TF_CLOUD_ORGANIZATION: "rakshith-kashyap"
  TF_API_TOKEN: "${{ secrets.TF_TOKEN }}"
  TF_WORKSPACE: "rakshith-test"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.4
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.4
        id: run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          plan_only: true

      - name: Get Plan Output
        id: plan-output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.4
        with:
          plan: ${{ steps.run.outputs.plan_id }}
          
      - name: Get Plan Output.....
        uses: hashicorp/tfc-workflows-github/actions/show-run@v1.0.4
        id: show-run
        with:
          run: ${{ steps.run.outputs.run_id }}
        env:
          TF_WORKSPACE: ${{ env.TF_WORKSPACE }} # Adding the workspace name to the environment
          
      - name: Display Run Link
        run: |
          run_id=${{ steps.run.outputs.run_id }}
          workspace=${{ env.TF_WORKSPACE }}
          run_link="https://app.terraform.io/app/${{ env.TF_CLOUD_ORGANIZATION }}/workspaces/${workspace}/runs/${run_id}"
          echo "Run Link: $run_link"
